[project]
name = "dismech-newton"
version = "0.1.0.post1"
description = "Discrete Elastic Rods for NVIDIA Newton."
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
keywords = ["discrete elastic rods", "rods", "simulation", "physics", "robotics", "newton", "warp", "gpu"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Environment :: GPU :: NVIDIA CUDA",
    "Topic :: Scientific/Engineering :: Physics",
]
authors = [
    { name = "ryanchaiyakul", email = "ryanchaiyakul@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "newton~=1.6.0",
    "scipy>=1.14",
]

[project.urls]
Homepage = "https://github.com/ryanchaiyakul/dismech-newton"
Issues = "https://github.com/ryanchaiyakul/dismech-newton/issues"

[project.optional-dependencies]
gpu = [
    "cupy-cuda13x>=14.2.0",
    "nvmath-python[cu13]>=1.0",
]
viewer = [
    "imgui-bundle>=1.92.900",
    "pyglet>=2.1.6,<3",
    "PyOpenGL>=3.1",
    "pillow>=10",
    "matplotlib>=3.8",
]
mujoco = [
    "gitpython>=3.1",
    "mujoco~=3.12.0",
    "mujoco-warp~=3.12.0",
    "pycollada>=0.9",
    "trimesh>=4",
]

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]
ignore = ["E741"]  # `l` for lengths in the math

[tool.ruff.lint.isort]
split-on-trailing-comma = false
