[project]
name = "dismech-newton"
version = "0.1.0"
description = "Discrete Elastic Rods for NVIDIA Newton."
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
keywords = ["discrete elastic rods", "rods", "simulation", "physics", "robotics", "newton", "warp", "gpu"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Environment :: GPU :: NVIDIA CUDA",
    "Topic :: Scientific/Engineering :: Physics",
]
authors = [
    { name = "ryanchaiyakul", email = "ryanchaiyakul@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "newton~=1.6.0",
    "scipy>=1.14",
]

[project.urls]
Homepage = "https://github.com/ryanchaiyakul/dismech-newton"
Issues = "https://github.com/ryanchaiyakul/dismech-newton/issues"

[project.optional-dependencies]
gpu = [
    "cupy-cuda13x>=14.2.0",
    "nvmath-python[cu13]>=1.0",
]
viewer = [
    "imgui-bundle>=1.92.900",
    "pyglet>=2.1.6,<3",
    "PyOpenGL>=3.1",
    "pillow>=10",
]

[build-system]
requires = ["uv_build>=0.12.20,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
